rule_set = [
    # Token must come first to correctly categorize stablecoins and wrapped tokens
    {"fields": [1,2], "terms": ["stablecoin", "token", "usdc", "usdt", "dai", "weth", "wbtc", "wrapped"], "exactMatchNecessary": "false", "category": "Token"},
    # Infrastructure must come before DEX to match "allowance holder" before "0x v2"
    {"fields": [1,2], "terms": ["entry point", "erc-4337", "safe", "proxy factory", "multi send", "disperse", "multisender", "permit2", "allowance holder", "approval proxy", "transparent upgradeable proxy", "dvn", "gelato", "chainlink", "automation", "oracle", "witnet", "api3", "redsnapper"], "exactMatchNecessary": "false", "category": "Infrastructure"},
    {"fields": [1,2], "terms": ["cex", "coinbase", "binance", "kraken", "ftx", "okx", "bittrex", "kucoin", "gemini", "hitbtc", "zb.com", "bitstamp", "poloniex", "crypto.com", "coinspaid", "shuffle.com", "rainbet.com", "mexc"], "exactMatchNecessary": "false", "category": "CEX"},
    {"fields": [1,2], "terms": ["opensea", "blur.io", "collectibles", "nft", "cryptokitties", "cryptoatoms", "cryptopunks", "cryptobots", "cryptodozer", "cryptograph", "cryptorome", "cryptosaga", "cryptospells", "cubeanz", "reservoir", "seadrop"], "exactMatchNecessary": "false", "category": "NFT"},
    {"fields": [1,2], "terms": ["dex", "swap", "uniswap", "balancer", "sushi", "1inch", "curve", "rango", "velora", "sorella", "beethoven x", "woofi", "bebop", "0x v2", "synfutures"], "exactMatchNecessary": "false", "category": "DEX"},
    {"fields": [1,2], "terms": ["lending","aave", "maker:", "justlend", "compound", "loan", "yield farming", "morpho"], "exactMatchNecessary": "false", "category": "Lending"},
    {"fields": [1,2], "terms": ["staking", "lido", "rocket", "beacon deposit"], "exactMatchNecessary": "false", "category": "Staking"},
    {"fields": [1,2], "terms": ["bridge", "across protocol", "li.fi", "layerzero", "mayan", "relay", "lighter", "fastcctp", "gas.zip", "gasmovr", "socket", "l2pass", "dln", "hinkal"], "exactMatchNecessary": "false", "category": "Bridge"},
    {"fields": [1,2], "terms": ["banana gun", "unibot","telegram", "maestrobots"], "exactMatchNecessary": "false", "category": "Bots"},
    {"fields": [1,2], "terms": ["ens:", "ens", "unstoppable domains", "space id"], "exactMatchNecessary": "false", "category": "Social"},
    {"fields": [1,2], "terms": ["social","worldid","verifiable credentials", "message transmitter"], "exactMatchNecessary": "false", "category": "Social"},
    {"fields": [1,2], "terms": ["gambling"], "exactMatchNecessary": "false", "category": "Gambling"},
    {"fields": [1,2], "terms": ["forsage"], "exactMatchNecessary": "false", "category": "Multi Level Marketing"},
    {"fields": [1,2], "terms": ["governance", "dao"], "exactMatchNecessary": "false", "category": "DAO"},
    {"fields": [1,2], "terms": ["mev", "jaredfromsubway", "sandwich", "frontrun", "backrun", "arbitrage bot", "flashbot", "rsync-builder", "cointool", "xen batch minter"], "exactMatchNecessary": "false", "category": "MEV"},
    {"fields": [1,2], "terms": ["fake_phishing", "phishing"], "exactMatchNecessary": "false", "category": "Phishing"},
    {"fields": [1,2], "terms": ["airdrop", "claim", "presale"], "exactMatchNecessary": "false", "category": "Airdrop"},
    {"fields": [1,2], "terms": ["System Contract"], "exactMatchNecessary": "false", "category": "System Contract"},
    {"fields": [1,2], "terms": ["sequencer", "batch submitter", "batcher", "base sequencer"], "exactMatchNecessary": "false", "category": "L2"},
    {"fields": [1,2], "terms": ["mailbox", "hyperlane"], "exactMatchNecessary": "false", "category": "Bridge"},
    {"fields": [1,2], "terms": ["uma", "angle protocol", "redstone", "voting v2"], "exactMatchNecessary": "false", "category": "DeFi"},
    {"fields": [1,2], "terms": ["refuel", "gas refuel", "gaslz", "gas.zip", "oftv2"], "exactMatchNecessary": "false", "category": "Bridge"},
    {"fields": [1,2], "terms": ["gaming", "game", "zed run", "degen arena", "estfor kingdom", "creepz", "dark forest"], "exactMatchNecessary": "false", "category": "Gaming"},
    {"fields": [1,2], "terms": ["kyber", "dodo", "maverick", "paraspace", "gains network", "fluid", "superfluid", "enso", "merkly", "connext", "dln"], "exactMatchNecessary": "false", "category": "DeFi"},
    {"fields": [1,2], "terms": ["celo", "tevaera", "aori", "meson", "layer3", "superform", "eternal ai", "openid3"], "exactMatchNecessary": "false", "category": "DeFi"},
    {"fields": [1,2], "terms": ["gooddollar", "hmx", "vfat"], "exactMatchNecessary": "false", "category": "DeFi"},
]